#python submit_slurm_signal.py --masses-a 0.220 --masses-dm 7000 --nevents 10000000 --depth -1500 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss
#python submit_slurm_signal.py --masses-a 0.220 --masses-dm 7000 --nevents 10000000 --depth -2000 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss
#python submit_slurm_signal.py --masses-a 0.220 --masses-dm 7000 --nevents 10000000 --depth -3000 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss
#python submit_slurm_signal.py --masses-a 0.220 --masses-dm 7000 --nevents 10000000 --depth -4000 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss
#python submit_slurm_signal.py --masses-a 0.220 --masses-dm 7000 --nevents 10000000 --ntrials 500 --depth -2000 --disk-radius 6000 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
# python submit_slurm_signal.py --masses-a 0.220 --masses-dm 7000 --nevents 10000000 --ntrials 50 --depth -1500 --disk-radius 6000 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
# python submit_slurm_signal.py --masses-a 0.220 --masses-dm 7000 --nevents 10000000 --ntrials 100 --depth -1800 --disk-radius 6000 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
# python submit_slurm_signal.py --masses-a 0.220 --masses-dm 7000 --nevents 10000000 --ntrials 500 --depth -1800 --disk-radius 6000 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
# python submit_slurm_signal.py --masses-a 0.220 --masses-dm 70000 --nevents 10000000 --ntrials 500 --depth -1500 --disk-radius 6000 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
# python submit_slurm_signal.py --masses-a 0.220 --masses-dm 7000 --nevents 100000 --ntrials 500 --depth -18 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
python submit_slurm_signal.py --masses-a 0.220 --masses-dm 100 --nevents 1000000 --ntrials 50 --depth -8 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
python submit_slurm_signal.py --masses-a 0.220 --masses-dm 1000 --nevents 1000000 --ntrials 50 --depth -8 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
python submit_slurm_signal.py --masses-a 0.220 --masses-dm 3000 --nevents 1000000 --ntrials 50 --depth -8 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
python submit_slurm_signal.py --masses-a 0.220 --masses-dm 7000 --nevents 1000000 --ntrials 50 --depth -8 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
python submit_slurm_signal.py --masses-a 0.220 --masses-dm 10000 --nevents 1000000 --ntrials 50 --depth -8 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42
python submit_slurm_signal.py --masses-a 0.220 --masses-dm 100000 --nevents 1000000 --ntrials 50 --depth -8 --dm-model momentum_constrained --save-to-file --output-directory OUTPUT_FILES --additional-tag TESTING --average-eloss --parallel --base-seed 42